### ISSUE TITLE
how to setup slack ............... key

### ISSUE THREAD

**Issue by balook** [ameenmaali/qsfuzz#1]
how to setup slack ............... key in which config ....file where is it location

**Comment by ameenmaali** [comment]
Are you referring to how to setup the Config for qsfuzz? If so, setup a Slack YAML key in your config file as it shows in this example: https://github.com/ameenmaali/qsfuzz/blob/master/config-example.yaml#L40

If you mean how to get the Slack token from Slack, you’ll need to create a Slack Workspace (free), then create an application, and get a bot token from the app that has access to write messages from the bot user. See this doc for a bit more info: https://api.slack.com/docs/token-types#bot
