### ISSUE TITLE
Installtion Problem 

### ISSUE THREAD

**Issue by impramodsargar** [ameenmaali/qsfuzz#10]
go get github.com/ameenmaali/qsfuzz                                                                                                                                                                                                     cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/root/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

**Comment by ameenmaali** [comment]
Hey @impramodsargar, if you have the following environment variable set `export GO111MODULE=on` and re-run the command it should work.

**Comment by impramodsargar** [comment]
Thanks it worked
