### ISSUE TITLE
Feature Request: [[originalValue]] Template String

### ISSUE THREAD

**Issue by spaceraccoon** [ameenmaali/qsfuzz#2]
To help with heuristics, it would also be great to have the original value of the query parameter represented by a template string like [[originalValue]].

So something like 

```
    injections:
      - [[originalValue]]'"><h2>asd</h2>'
```

So rather than completely replacing the query string value, you simply append to it. I'm not sure how you would ensure that [[originalValue]] is different if a URL has more than one query parameter though.

**Comment by ameenmaali** [comment]
Great idea, will be useful. I'll work on this :)

**Comment by ameenmaali** [comment]
Thanks again for the suggestion @spaceraccoon, I just pushed a new commit (https://github.com/ameenmaali/qsfuzz/commit/edf7b49a7f98543186a51c130f1c152dfbfc7d5f) that added this functionality. It's pretty shoddy, but this whole thing made me realize I should probably invest in a more robust templating system/logic to make adding new ones easier 😄
